# Generated by Django 5.2.3 on 2025-06-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
